substitutions:
  _SERVICE: "edgepicks"   # change if you want another Cloud Run service name
  _REGION: "us-west2"     # set to your region

steps:
- name: "gcr.io/cloud-builders/docker"
  id: "Build Docker image"
  args: ["build", "-t", "us-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE:$_COMMIT_SHA", "."]

- name: "gcr.io/cloud-builders/docker"
  id: "Push Docker image"
  args: ["push", "us-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE:$_COMMIT_SHA"]

- name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
  id: "Deploy to Cloud Run"
  entrypoint: gcloud
  args:
    [
      "run","deploy","$_SERVICE",
      "--image","us-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE:$_COMMIT_SHA",
      "--region","$_REGION",
      "--platform","managed",
      "--allow-unauthenticated",
      "--port","8080",
      "--cpu","1",
      "--memory","512Mi",
      "--max-instances","10",
      "--set-env-vars","NEXT_TELEMETRY_DISABLED=1,HOSTNAME=0.0.0.0"
    ]

images:
- "us-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE:$_COMMIT_SHA"
