export const REQUIRED_ENV_KEYS = [
  'GOOGLE_CLIENT_ID',
  'GOOGLE_CLIENT_SECRET',
  'SUPABASE_KEY',
  'SUPABASE_URL',
  'NEXTAUTH_SECRET',
  'SPORTS_API_KEY',
  'LIVE_MODE',
  'PREDICTION_CACHE_TTL_SEC',
  'MAX_FLOW_CONCURRENCY',
] as const;
