name: Percy Snapshots

on:
  pull_request:

jobs:
  percy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run start &
      - run: npx wait-on http://localhost:3000
      - run: npx playwright install --with-deps
      - run: npx percy exec -- npx playwright test tests/visual/percy.spec.ts
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
